avatar:
  author_photo: /images/zpy.jpg
  path: /

title: zpyqaq`s Blog 
  


footer: © 2021, Built on 2021/2/21 11:04 PM using Hexo
signature: Freshman majoring in software engineering,Recently learning Japanese,Web front-end and Linux