avatar:
  author_photo: /images/zpy.jpg
  path: /

menu:
  Home: /
  About: /about

signature: Freshman majoring in software engineering,Recently learning Japanese,Web front-end and Linux
background-image: /images/bg.jpg
footer: © 2021, Built on 2021/2/21 11:04 PM using Hexo

